In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(np.mean(a))

[5 7 9]
[ 4 10 18]
2.0


In [3]:
arr=np.array([[1,2],[3,4]])
print(arr.shape)

(2, 2)


In [5]:
np.zeros((2,3))
np.ones((3,3))
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
arr=np.array([2,4,6,8])
print(arr[1:3])

[4 6]


In [8]:
np.sqrt(arr)
np.sum(arr)
np.max(arr)
np.min(arr)

np.int64(2)

In [ ]:
#matrix
c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])
np.dot(c,d)

array([[19, 22],
       [43, 50]])

In [10]:
v=np.array([2,4])
magnitude=np.sqrt(np.sum(v**2))
print(magnitude)

4.47213595499958


In [11]:
a=np.array([1,2])
b=np.array([3,4])
print(a+b)
print(a*b)
print(2*a)

[4 6]
[3 8]
[2 4]


In [12]:
A=np.array([1,2])
B=np.array([3,4])
midpoint=(A+B)/2
print(midpoint)


[2. 3.]


In [13]:
a = np.array([0, 0])
b = np.array([4, 0])
c = np.array([4, 3])

area = 0.5 * np.linalg.norm(np.cross(b-a, c-a))
print(area)  

6.0


C:\Users\durga\AppData\Local\Temp\ipykernel_71136\432034665.py:5: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  area = 0.5 * np.linalg.norm(np.cross(b-a, c-a))


In [15]:
#pandas
import pandas as pd
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64


In [17]:
data={
    "Name":["Durga","Pravin"],
    "Marks":[75,80]
}
df=pd.DataFrame(data)
print(df)

     Name  Marks
0   Durga     75
1  Pravin     80


In [20]:

df=pd.read_csv("C:/Users/durga/OneDrive/Documents/data1.csv")
print(df)

   Roll_number          Name Internship_duration  Joining_date Courses
0          101  Durga Prasad            3 months  June 12,2026    Java
1          102          Ravi            6 months  June 12,2026  Python
2          103        Ashish            3 months  June 12,2026   UI/UX
3          104        Shahid            6 months  June 12,2026    Java
4          105         Bilal            3 months  June 12,2026  Python


In [22]:
print(df.head(1))

   Roll_number          Name Internship_duration  Joining_date Courses
0          101  Durga Prasad            3 months  June 12,2026    Java


In [23]:
print(df.head(2))

   Roll_number          Name Internship_duration  Joining_date Courses
0          101  Durga Prasad            3 months  June 12,2026    Java
1          102          Ravi            6 months  June 12,2026  Python


In [24]:
print(df.tail())

   Roll_number          Name Internship_duration  Joining_date Courses
0          101  Durga Prasad            3 months  June 12,2026    Java
1          102          Ravi            6 months  June 12,2026  Python
2          103        Ashish            3 months  June 12,2026   UI/UX
3          104        Shahid            6 months  June 12,2026    Java
4          105         Bilal            3 months  June 12,2026  Python


In [25]:
print(df.tail(1))

   Roll_number   Name Internship_duration  Joining_date Courses
4          105  Bilal            3 months  June 12,2026  Python


In [26]:
print(df.tail(2))

   Roll_number    Name Internship_duration  Joining_date Courses
3          104  Shahid            6 months  June 12,2026    Java
4          105   Bilal            3 months  June 12,2026  Python


In [27]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Roll_number          5 non-null      int64 
 1   Name                 5 non-null      object
 2   Internship_duration  5 non-null      object
 3   Joining_date         5 non-null      object
 4   Courses              5 non-null      object
dtypes: int64(1), object(4)
memory usage: 328.0+ bytes
None


In [28]:
print(df["Name"])

0    Durga Prasad
1            Ravi
2          Ashish
3          Shahid
4           Bilal
Name: Name, dtype: object


In [31]:
print(df["Internship_duration"])

0    3 months
1    6 months
2    3 months
3    6 months
4    3 months
Name: Internship_duration, dtype: object


In [34]:
print(df[["Roll_number","Name"]])

   Roll_number          Name
0          101  Durga Prasad
1          102          Ravi
2          103        Ashish
3          104        Shahid
4          105         Bilal
